services:
  - type: web
    name: rekanwal-app
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.11.0
